### ISSUE TITLE
looks like instructions are for version 2.8 but folder structures/names are different in version 3+?

### ISSUE THREAD

**Issue by JustinGOSSES** [bruffridge/nasawds#5]
Was confused when trying to follow the instructions. 

Looks like instructions are for version 2.8 but folder structures/names are different in version 3+?

Might be worth noting this is NASA WDS readme if you're dependent on USWDS to fix instructions???

**Comment by bruffridge** [comment]
NASAWDS versioning is separate from USWDS, so even though NASAWDS is at v3, USWDS latest version is still v2. A little confusing I know, but since we're following semver, I made a breaking change awhile ago and had to bump the major version of NASAWDS. Let me know what you are trying to do that didn't make sense in the USWDS docs, and I can update the README.
